spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:~/acmebank
    username: sa
    password: password
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
  h2:
    console:
      enabled: true